# Generated by Django 5.2 on 2025-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adrress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
