# Generated by Django 5.2 on 2025-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='r_image',
            field=models.ImageField(upload_to='recipies/'),
        ),
    ]
